/**
 * @fileoverview gRPC-Web generated client stub for questions
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: question.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.questions = require('./question_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.questions.QuestionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.questions.QuestionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.questions.GetQuestionsRequest,
 *   !proto.questions.GetQuestionsResponse>}
 */
const methodDescriptor_QuestionService_GetQuestions = new grpc.web.MethodDescriptor(
  '/questions.QuestionService/GetQuestions',
  grpc.web.MethodType.UNARY,
  proto.questions.GetQuestionsRequest,
  proto.questions.GetQuestionsResponse,
  /**
   * @param {!proto.questions.GetQuestionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.questions.GetQuestionsResponse.deserializeBinary
);


/**
 * @param {!proto.questions.GetQuestionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.questions.GetQuestionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.questions.GetQuestionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.questions.QuestionServiceClient.prototype.getQuestions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/questions.QuestionService/GetQuestions',
      request,
      metadata || {},
      methodDescriptor_QuestionService_GetQuestions,
      callback);
};


/**
 * @param {!proto.questions.GetQuestionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.questions.GetQuestionsResponse>}
 *     Promise that resolves to the response
 */
proto.questions.QuestionServicePromiseClient.prototype.getQuestions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/questions.QuestionService/GetQuestions',
      request,
      metadata || {},
      methodDescriptor_QuestionService_GetQuestions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.questions.GetQuestionByIdRequest,
 *   !proto.questions.GetQuestionByIdResponse>}
 */
const methodDescriptor_QuestionService_GetQuestionById = new grpc.web.MethodDescriptor(
  '/questions.QuestionService/GetQuestionById',
  grpc.web.MethodType.UNARY,
  proto.questions.GetQuestionByIdRequest,
  proto.questions.GetQuestionByIdResponse,
  /**
   * @param {!proto.questions.GetQuestionByIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.questions.GetQuestionByIdResponse.deserializeBinary
);


/**
 * @param {!proto.questions.GetQuestionByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.questions.GetQuestionByIdResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.questions.GetQuestionByIdResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.questions.QuestionServiceClient.prototype.getQuestionById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/questions.QuestionService/GetQuestionById',
      request,
      metadata || {},
      methodDescriptor_QuestionService_GetQuestionById,
      callback);
};


/**
 * @param {!proto.questions.GetQuestionByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.questions.GetQuestionByIdResponse>}
 *     Promise that resolves to the response
 */
proto.questions.QuestionServicePromiseClient.prototype.getQuestionById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/questions.QuestionService/GetQuestionById',
      request,
      metadata || {},
      methodDescriptor_QuestionService_GetQuestionById);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.questions.SearchQuestionRequest,
 *   !proto.questions.GetQuestionsResponse>}
 */
const methodDescriptor_QuestionService_SearchQuestion = new grpc.web.MethodDescriptor(
  '/questions.QuestionService/SearchQuestion',
  grpc.web.MethodType.UNARY,
  proto.questions.SearchQuestionRequest,
  proto.questions.GetQuestionsResponse,
  /**
   * @param {!proto.questions.SearchQuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.questions.GetQuestionsResponse.deserializeBinary
);


/**
 * @param {!proto.questions.SearchQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.questions.GetQuestionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.questions.GetQuestionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.questions.QuestionServiceClient.prototype.searchQuestion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/questions.QuestionService/SearchQuestion',
      request,
      metadata || {},
      methodDescriptor_QuestionService_SearchQuestion,
      callback);
};


/**
 * @param {!proto.questions.SearchQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.questions.GetQuestionsResponse>}
 *     Promise that resolves to the response
 */
proto.questions.QuestionServicePromiseClient.prototype.searchQuestion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/questions.QuestionService/SearchQuestion',
      request,
      metadata || {},
      methodDescriptor_QuestionService_SearchQuestion);
};


module.exports = proto.questions;

